### List All
GET http://localhost:8080/api/notifications
Accept: application/vnd.example.v2+json

### Get First
GET http://localhost:8080/api/notifications/1

### Try to get a non existent
GET http://localhost:8080/api/notifications/9999

### Create new
POST http://localhost:8080/api/notifications
Content-Type: application/json

{
    "message":"My new message"
}

### Try no change
PUT http://localhost:8080/api/notifications/3
Content-Type: application/json

{
    "id": 3,
    "message":"My changed message"
}

### Check ID validation
PUT http://localhost:8080/api/notifications/3
Content-Type: application/json
{
    "id": 4,
    "message":"Id Mismatch"
}

### Get Image
GET http://localhost:8080/api/images/not_exist.jpg
Accept: image/jpeg

### SSE
GET http://localhost:8080/api/events
Content-Type: text/plain

### Web Sockets
curl --include \
     --no-buffer \
     --header "Connection: Upgrade" \
     --header "Upgrade: websocket" \
     --header "Host: localhost:8080" \
     --header "Origin: http://localhost:8080" \
     --header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
     --header "Sec-WebSocket-Version: 13" \
     http://localhost:8080/chat/name